### ISSUE TITLE
Phần list tin tức hiển thị chưa đúng với UX

### ISSUE THREAD

**Issue by phuongbkatp** [phuongbkatp/manutdvn#7]
![screenshot_1514044631](https://user-images.githubusercontent.com/32545917/34320834-b6f46cc8-e834-11e7-889a-3a88d5cda59d.png)
![screenshot_1514044647](https://user-images.githubusercontent.com/32545917/34320835-b7b0c17a-e834-11e7-9ee9-5773c0d307ab.png)
![screenshot_1514044654](https://user-images.githubusercontent.com/32545917/34320836-b7e23c8c-e834-11e7-85ca-0ea7560d6846.png)

**Comment by phuongbkatp** [comment]
- Tab tin tức thứ 3 là "Bình luận" ( nghĩa là tin về các bài bình luận của chuyên gia) chứ không phải hiển thị comment.
- Phần danh sách tin tức , các item có margin khoảng 8dp, thẳng hàng nhau chứ hiện tại có type 2,3 chưa có magin.
- 3 type 1,2,3 đều chưa có đổ bóng ở viền.
- type 3  hiển hị sai, title không đè lên ảnh.
- type 2 và 3 do có chữ đè lên ảnh nên cần có màn che mờ mờ phía trước ảnh để gradient, như bên android là     <gradient
        android:angle="90"
        android:centerColor="#33000000"
        android:endColor="#09000000"
        android:startColor="#59000000" />
.

**Comment by searain91** [comment]
Đã fix
